name: "Check and reject ANY spam PRs"
description: "Run basic checks and close & mark ANY spam PRs"
author: "Andrey Slotin, mod by Asmodat"
inputs:
  access_token:
    description: "GitHub access token"
    required: true
  spam_label:
    description: "Spam label text"
    required: false
    default: "Spam"
  close_spam_prs:
    description: "Automatically closes ANY spam PRs (yes/no)?"
    required: false
    default: "yes"
runs:
  using: docker
  image: "Dockerfile"
branding:
  icon: "thumbs-down"
  color: "red"
