name: Spam filter - asmodat mod
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Rummelsnuff
        uses: asmodat/rummelsnuff@master
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
